<?php
/**
 * The main template file
 *
 * This is the most generic template file in a WordPress theme
 * and one of the two required files for a theme (the other being style.css).
 * It is used to display a page when nothing more specific matches a query.
 * E.g., it puts together the home page when no home.php file exists.
 */


/**
 * Load the header for the website - this contains all of the meta information which is generated by wordpress!
 */
get_header();
?>


<?php

/**
 * Load the footer for the website - this closes the body tag and imports the footer.
 */
get_footer();

?>
