<?php

/**
 * The single template for the "post" post type. Each post type can have a template file.
 */


/**
 * Load the header for the website - this contains all of the meta information which is generated by wordpress!
 */
get_header();
?>

<article class="container">
    <div class="row">
        <div class="col-12">
            <h2><?php the_title() ?></h2>
            <div class="content">
                <?php the_content() ?>
            </div>
        </div>
    </div>
</article>

<?php

/**
 * Load the footer for the website - this closes the body tag and imports the footer.
 */
get_footer();

?>
